services:
  site-angular:
    build: .
    restart: unless-stopped
    networks:
      - internal-aluguel
    depends_on:
      - postgres
  
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aluguel_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal-aluguel

networks:
  internal-aluguel:
    driver: bridge

volumes:
  postgres_data: